# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
    - name: Deploy using ssh
#       uses: actions/setup-node@v3
      uses: appleboy/ssh-action@v0.1.10
      with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/domains/boilerplate.tailwave.io/public_html
          git pull origin main
          git status
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          npm install --only=prod
          npm run generate
#     - run: npm ci
#     - run: npm run generate --if-present
